// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHThpnP0UevJkgBATyQe14IjgXstS9poc',
    appId: '1:139289156897:web:0701304d9dd91ae6543260',
    messagingSenderId: '139289156897',
    projectId: 'fooddelivery-2eb3a',
    authDomain: 'fooddelivery-2eb3a.firebaseapp.com',
    storageBucket: 'fooddelivery-2eb3a.appspot.com',
    measurementId: 'G-44J5MJ6Y0T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJj7-2SWXdsOCyCFqbeZY3WtoKlPRQ45A',
    appId: '1:139289156897:android:c7da6e0466ef328b543260',
    messagingSenderId: '139289156897',
    projectId: 'fooddelivery-2eb3a',
    storageBucket: 'fooddelivery-2eb3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwE0fAOrZSymN6UwaRpvFNlczIa_cb0ms',
    appId: '1:139289156897:ios:513d8759149420ce543260',
    messagingSenderId: '139289156897',
    projectId: 'fooddelivery-2eb3a',
    storageBucket: 'fooddelivery-2eb3a.appspot.com',
    iosBundleId: 'com.example.foodDelivery',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwE0fAOrZSymN6UwaRpvFNlczIa_cb0ms',
    appId: '1:139289156897:ios:b1078a987a666fa5543260',
    messagingSenderId: '139289156897',
    projectId: 'fooddelivery-2eb3a',
    storageBucket: 'fooddelivery-2eb3a.appspot.com',
    iosBundleId: 'com.example.foodDelivery.RunnerTests',
  );
}
